/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import EDD.Arbol;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Luis
 */
public class Cargar extends javax.swing.JFrame {
    /**
     * El diccionario de palabras cargado desde el archivo.
     */
    public String[] diccionario;

    /**
     * El arbol que representa la sopa de letras cargada desde el archivo.
     */
    public Arbol arbol;

    /**
     * La instancia de la ventana men&uaccute.
     */
    public static Menu v1;

    /**
     * Crea una nueva instancia de la clase {@code Cargar}. Inicializa los
     * componentes y configura la ventana.
     */

    /**
     * Creates new form Buscador
     */
    public Cargar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        botonAtras.setEnabled(true);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ruta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cargarArchivo = new javax.swing.JTextArea();
        Car = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ruta.setBackground(new java.awt.Color(0, 0, 102));
        ruta.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, 40));

        cargarArchivo.setBackground(new java.awt.Color(0, 0, 102));
        cargarArchivo.setColumns(20);
        cargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        cargarArchivo.setRows(5);
        jScrollPane1.setViewportView(cargarArchivo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 160));

        Car.setBackground(new java.awt.Color(0, 0, 102));
        Car.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        Car.setForeground(new java.awt.Color(255, 255, 255));
        Car.setText("Cargar");
        Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarActionPerformed(evt);
            }
        });
        jPanel1.add(Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 40));

        Buscar.setBackground(new java.awt.Color(0, 0, 102));
        Buscar.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 120, 40));

        botonAtras.setBackground(new java.awt.Color(0, 0, 102));
        botonAtras.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Atras");
        botonAtras.setActionCommand("botonAtras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/360_F_281966380_17LnnpANRTABwsBe38pGEOCLLjMPSqtJ.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarActionPerformed
        // TODO add your handling code here:
        if (cargarArchivo != null) {
            

            this.setVisible(false);
            Bienvenida b = new Bienvenida();
            Menu menu = new Menu(this);
            menu.setVisible(true);
            
        }
    }//GEN-LAST:event_CarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        // Creo el Objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        // Creo el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        // Le indico el filtro
        fc.setFileFilter(filtro);

        // Abrimos la ventana, guardamos la op seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);

        // Si el usuario presiona aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Selecciono el fichero
            File fichero = fc.getSelectedFile();
           this.ruta.setText(fichero.getAbsolutePath());

try (FileReader fr = new FileReader(fichero); 
     BufferedReader br = new BufferedReader(fr)) {
    
    StringBuilder contenido = new StringBuilder();
    StringBuilder datosDiccionario = new StringBuilder();
    int modo = 0; // 0 = diccionario, 1 = tabla
    
    String linea;
    while ((linea = br.readLine()) != null) {
        if (linea.equals("dic")) {
            modo = 0;
        } else if (linea.equals("/dic")) {
            modo = 0;
        } else if (linea.equals("tab")) {
            modo = 1;
        } else if (linea.equals("/tab")) {
            modo = 0;
        } else if (modo == 0) {
            datosDiccionario.append(linea).append(",");
        } else {
            linea = linea.replace(",", "");
            this.arbol = new Arbol(linea.length(), linea);
        }
        contenido.append(linea).append("\n");
    }
    
    this.diccionario = datosDiccionario.length() > 0 
            ? datosDiccionario.toString().split(",") 
            : new String[0];
    
    this.cargarArchivo.setText(contenido.toString());
    botonAtras.setEnabled(true);
    
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, 
            "Error al leer el archivo: " + e.getMessage(),
            "Error", 
            JOptionPane.ERROR_MESSAGE);
}
    }
                                         
    }//GEN-LAST:event_BuscarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        Bienvenida menu = new Bienvenida ();

        menu.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Car;
    private javax.swing.JButton botonAtras;
    private javax.swing.JTextArea cargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables
}
